module.exports = {
	env: {
		browser: true,
		node: true,
	},
	parserOptions: {
		parser: 'babel-eslint',
	},
	extends: [
		'eslint:recommended',
		'plugin:vue/strongly-recommended',
	],
	plugins: [
		'vue',
	],
	rules: {
		//<editor-fold desc="eslint basics">
		semi: ['error', 'always'],
		curly: 'error',
		eqeqeq: ['error', 'always'],
		quotes: ['error', 'single',],
		indent: ['error', 'tab'],
		'array-bracket-spacing': ['error', 'always'],
		'block-spacing': ['error'],
		'no-trailing-spaces': ['error'],
		'no-const-assign': ['error'],
		'no-mixed-spaces-and-tabs': ['error'],
		'comma-dangle': ['error', 'always-multiline'], // always
		'max-statements-per-line': ['error', { max: 1 }],
		'prefer-arrow-callback': ['error'],
		'default-param-last': ['error'],
		'dot-notation': 'error',
		'brace-style': ['error', 'stroustrup', {
			allowSingleLine: false,
		}],
		'no-unreachable-loop': 'error',
		'newline-per-chained-call': 'error',
		'eol-last': ['error', 'never',],
		'no-var': 2,
		'no-tabs': 0,
		'no-promise-executor-return': 2,
		//</editor-fold>

		//<editor-fold desc="vue rules">
		'vue/order-in-components': 'error',
		'vue/this-in-template': 'error',
		'vue/require-prop-types': 'error',
		'vue/component-tags-order': 'error',
		'vue/no-lone-template': 'error',
		'vue/attributes-order': 'error',
		'vue/component-name-in-template-casing': ['error', 'kebab-case'],
		'vue/no-empty-component-block': 'error',
		'vue/component-definition-name-casing': 'error',
		'vue/no-boolean-default': ['error', 'default-false'],
		'vue/html-closing-bracket-newline': ['error', {
			singleline: 'never',
			multiline: 'never',
		}],
		'vue/max-attributes-per-line': ['error', {
			singleline: {
				max: 3,
			},
			multiline: {
				max: 1,
			},
		}],
		'vue/html-indent': ['error', 'tab'],
		'vue/no-v-html': 0,
		'vue/mustache-interpolation-spacing': ['error', 'always'],
		'vue/html-self-closing': 'error',
		'vue/attribute-hyphenation': ['error', 'always'],
		'vue/no-multiple-slot-args': 'error',
		'vue/v-on-event-hyphenation': ['error', 'always', {
			autofix: false, // recommended to disable the autofix
		}],
		'vue/no-template-shadow': 'error',
		'vue/v-on-function-call': ['error'],
		'vue/custom-event-name-casing': 'error',
		'vue/no-restricted-v-bind': ['error', '/^v-/'],
		'vue/singleline-html-element-content-newline': ['error', {
			ignores: [
				'a',
				'abbr',
				'audio',
				'b',
				'bdi',
				'bdo',
				'canvas',
				'cite',
				'code',
				'data',
				'del',
				'dfn',
				'em',
				'i',
				'iframe',
				'ins',
				'kbd',
				'label',
				'map',
				'mark',
				'noscript',
				'object',
				'output',
				'picture',
				'q',
				'ruby',
				's',
				'samp',
				'small',
				'span',
				'strong',
				'sub',
				'sup',
				'svg',
				'time',
				'u',
				'var',
				'video',
				'td',
				'th',
				'router-link',
			],
		}],
		//</editor-fold>
	},
};