module.exports = {
	rules: {
		'vue/order-in-components': 'error',
		'vue/this-in-template': 'error',
		'vue/require-prop-types': 'error',
		'vue/component-tags-order': 'error',
		'vue/no-lone-template': 'error',
		'vue/attributes-order': 'error',
		'vue/component-definition-name-casing': 'error',
		'vue/html-self-closing': 'error',
		'vue/no-template-shadow': 'error',
		'vue/no-multiple-slot-args': 'error',
		'vue/no-v-html': 0,
		'vue/v-on-handler-style': 0,
		'vue/no-boolean-default': ['error', 'default-false'],
		'vue/html-indent': ['error', 'tab'],
		'vue/mustache-interpolation-spacing': ['error', 'always'],
		'vue/attribute-hyphenation': ['error', 'always'],
		'vue/no-restricted-v-bind': ['error', '/^v-/'],
		'vue/v-on-event-hyphenation': ['error', 'always', {
			autofix: false, // recommended to disable the autofix
		}],
		'vue/html-closing-bracket-newline': ['error', {
			singleline: 'never',
			multiline: 'never',
		}],
		'vue/max-attributes-per-line': ['error', {
			singleline: {
				max: 3,
			},
			multiline: {
				max: 1,
			},
		}],
		'vue/singleline-html-element-content-newline': ['error', {
			ignores: [
				'a',
				'abbr',
				'audio',
				'b',
				'bdi',
				'bdo',
				'canvas',
				'cite',
				'code',
				'data',
				'del',
				'dfn',
				'em',
				'i',
				'iframe',
				'ins',
				'kbd',
				'label',
				'map',
				'mark',
				'noscript',
				'object',
				'output',
				'picture',
				'q',
				'ruby',
				's',
				'samp',
				'small',
				'span',
				'strong',
				'sub',
				'sup',
				'svg',
				'time',
				'u',
				'var',
				'video',
				'td',
				'th',
				'router-link',
			],
		}],

		'vue/component-name-in-template-casing': ['error', 'kebab-case'],
		'vue/no-empty-component-block': 'error',
	}
}