import vue from 'eslint-plugin-vue';

export default [
  ...vue.configs['flat/recommended'],
  {
    rules: {
      'vue/order-in-components': 'error',
      'vue/this-in-template': 'error',
      'vue/require-prop-types': 'error',
      'vue/no-lone-template': 'error',
      'vue/attributes-order': 'error',
      'vue/component-definition-name-casing': 'error',
      'vue/html-self-closing': 'error',
      'vue/no-template-shadow': 'error',
      'vue/no-multiple-slot-args': 'error',
      'vue/no-v-html': 0,
      'vue/v-on-handler-style': 0,
      'vue/no-boolean-default': ['error', 'default-false'],
      'vue/html-indent': ['error', 2],
      'vue/mustache-interpolation-spacing': ['error', 'always'],
      'vue/attribute-hyphenation': ['error', 'always'],
      'vue/prefer-true-attribute-shorthand': ['error',],
      'vue/no-useless-mustaches': ['error',],
      'vue/no-useless-v-bind': ['error',],
      'vue/no-useless-concat': ['error',],
      'vue/block-order': ['error', {
        order: [
          ['template', 'script',],
          'style',
        ],
      },],
      'vue/no-restricted-v-bind': ['error', '/^v-/'],
      'vue/v-on-event-hyphenation': ['error', 'always', {
        autofix: false, // recommended to disable the autofix
      }],
      'vue/html-closing-bracket-newline': ['error', {
        singleline: 'never',
        multiline: 'always',
      }],
      'vue/max-attributes-per-line': ['error', {
        singleline: {
          max: 5,
        },
        multiline: {
          max: 1,
        },
      }],
      'vue/singleline-html-element-content-newline': ['error', {
        ignores: [
          'a',
          'abbr',
          'audio',
          'b',
          'bdi',
          'bdo',
          'canvas',
          'cite',
          'code',
          'data',
          'del',
          'dfn',
          'em',
          'i',
          'iframe',
          'ins',
          'kbd',
          'label',
          'map',
          'mark',
          'noscript',
          'object',
          'output',
          'picture',
          'q',
          'ruby',
          's',
          'samp',
          'small',
          'span',
          'strong',
          'sub',
          'sup',
          'svg',
          'time',
          'u',
          'var',
          'video',
          'td',
          'th',
          'router-link',
        ],
      }],

      'vue/component-name-in-template-casing': ['error', 'PascalCase'],
      'vue/no-empty-component-block': 'error',
      'vue/require-component-is': 'off',
      'vue/no-v-text-v-html-on-component': 'off',
      'vue/prefer-define-options': ['error',],
      'vue/custom-event-name-casing': ['error', 'camelCase'],
      'vue/define-macros-order': ['error', {
        order: [
          'defineProps',
          'defineEmits',
        ],
        "defineExposeLast": true,
      }],
    },
  },
];